@ECHO OFF

@REM TITLE
TITLE SERVER

@REM APPLICATION DIRETORY
SET APPDIRETORY=C:\Service\src\

@REM PATH FOR APPLICATION
SET PATHTOAPP=%PATHTOAPP%server.jar

@REM PATH FOR JAVA
SET PATHTOJAVA=java

%PATHTOJAVA% -jar %PATHTOAPP%