@ECHO OFF

@REM TITLE
TITLE INSTALL

@REM APPLICATION DIRETORY
SET APPDIRETORY=C:\Service\

@REM SERVICE INFORMATIONS
SET SERVICENAME=PRINTERSERVICE
SET DISPLAYNAME=Printer Service
SET DESCRIPTION=Service for print on printers in this computer
SET SERVICEDIRETORY=%APPDIRETORY%src

@REM LOGS DIRETORY
SET LOGDIRETORYIN=%APPDIRETORY%logs\log_in.txt
SET LOGDIRETORYOUT=%APPDIRETORY%logs\log_out.txt
SET LOGDIRETORYERR=%APPDIRETORY%logs\log_err.txt

@REM PATH FOR NSSM
SET PATHTONSSM=%APPDIRETORY%lib\nssm-2.24\win64\nssm.exe

@REM PATH FOR .BAT FILE
SET PATHTOBAT=%SERVICEDIRETORY%\server.bat

@REM PATH FOR APPLICATION TO START SERVICE
SET COMNET=net

"%PATHTONSSM%" install "%SERVICENAME%" "%PATHTOBAT%"

"%PATHTONSSM%" set "%SERVICENAME%" Application "%PATHTOBAT%"

"%PATHTONSSM%" set "%SERVICENAME%" AppDirectory "%SERVICEDIRETORY%"

"%PATHTONSSM%" set "%SERVICENAME%" AppParameters test

"%PATHTONSSM%" set "%SERVICENAME%" DisplayName "%DISPLAYNAME%"

"%PATHTONSSM%" set "%SERVICENAME%" Description "%DESCRIPTION%"

"%PATHTONSSM%" set "%SERVICENAME%" Start SERVICE_AUTO_START

"%PATHTONSSM%" set "%SERVICENAME%" AppStdin "%LOGDIRETORYIN%"

"%PATHTONSSM%" set "%SERVICENAME%" AppStdout "%LOGDIRETORYOUT%"

"%PATHTONSSM%" set "%SERVICENAME%" AppStderr "%LOGDIRETORYERR%"

%COMNET% start "%SERVICENAME%"

::pause