@ECHO OFF

@REM TITLE
TITLE UNINSTALL

@REM SERVICE INFORMATIONS
SET SERVICENAME=PRINTERSERVICE

@REM APPLICATION DIRETORY
SET APPDIRETORY=C:\Service\

@REM PATH FOR NSSM
SET PATHTONSSM=%APPDIRETORY%lib\nssm-2.24\win64\nssm.exe

@REM PATH FOR APPLICATION TO STOP SERVICE
SET COMNET=net

%COMNET% stop "%SERVICENAME%"

"%PATHTONSSM%" remove "%SERVICENAME%" confirm

::pause